package postgres

import (
	models "github.com/artumont/dotslashstream/internal/platform/postgres/models"
)

// Tables is the list of all Bun model types that need table creation.
// AUTO-GENERATED by scripts/gen_registry.py — do not edit manually.
var Tables = []any{
	(*models.Invite)(nil),
	(*models.Settings)(nil),
	(*models.User)(nil),
}
