#!/usr/bin/env python3
"""Auto-generate internal/platform/postgres/registry.go from model structs.

Scans all .go files in the models directory for structs embedding bun.BaseModel
with a bun:"table:..." tag, then emits the Tables slice used by createTables().

Usage:
    python3 scripts/gen_registry.py

Zero dependencies — stdlib only.
"""

import os
import re
import sys

MODELS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "internal", "platform", "postgres", "models"
)
OUTPUT_FILE = os.path.join(
    os.path.dirname(__file__), "..", "internal", "platform", "postgres", "registry.go"
)

# Matches: type Foo struct { bun.BaseModel `bun:"table:...,alias:...` }
STRUCT_RE = re.compile(
    r'type\s+(\w+)\s+struct\s*\{[^}]*bun\.BaseModel\s+`bun:"table:([^"]+)"',
    re.DOTALL,
)

PKG = "github.com/artumont/dotslashstream/internal/platform/postgres/models"

HEADER = """\
package postgres

import (
\tmodels "{pkg}"
)

// Tables is the list of all Bun model types that need table creation.
// AUTO-GENERATED by scripts/gen_registry.py — do not edit manually.
var Tables = []any{{
""".format(pkg=PKG)


def scan_models() -> list[str]:
    """Return sorted list of struct names that have bun table tags."""
    structs = []
    for fname in sorted(os.listdir(MODELS_DIR)):
        if not fname.endswith(".go") or fname.endswith("_test.go"):
            continue
        path = os.path.join(MODELS_DIR, fname)
        content = open(path).read()
        for match in STRUCT_RE.finditer(content):
            structs.append(match.group(1))
    return sorted(set(structs))


def generate(structs: list[str]) -> str:
    """Generate the registry.go file content."""
    if not structs:
        print("error: no model structs found", file=sys.stderr)
        sys.exit(1)

    lines = [HEADER]
    for name in structs:
        lines.append('\t(*models.{name})(nil),\n'.format(name=name))
    lines.append("}\n")
    return "".join(lines)


def main():
    structs = scan_models()
    content = generate(structs)

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(content)

    print("generated registry.go with {} model(s): {}".format(
        len(structs), ", ".join(structs)
    ))


if __name__ == "__main__":
    main()
